package com.api.demo.controllers;

public enum DealStates {
	NEW,
	PURCHASE_AGREEMENT_IN_PROGRESS,
	PURCHASE_AGREEMENT_SUBMITTED,
	PURCHASE_AGREEMENT_EXECUTED,
	PURCHASE_AGREEMENT_CLOSED,
	CHANGE_ORDER_IN_PROGRESS,
	CHANGE_ORDER_SUBMITTED,
	CHANGE_ORDER_EXECUTED,
	CHANGE_ORDER_CLOSED,
	REVISED_AGREEMENT_IN_PROGRESS,
}
